services:
  - type: web
    name: envo-userbot
    env: python
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers=1 --timeout=120 main:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: envo-postgres
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_SESSION_STRING
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: envo-postgres
    plan: free
